# name of workwlow, can be any
name: First Workflow
# name of event whet workflow is running
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbay
        run: echo "Done - buy!"
